## NOTE: Legacy development compose
## Prefer using `docker-compose.local.yml` for Local Dev (fixed Postgres 5434, Redis 6379).
## Do not run this concurrently with the Integration stack.
version: '3.8'

services:
  db:
    # image: postgres:15 # Use a specific Postgres version (e.g., 15) # <- Comment out or remove old line
    image: postgis/postgis:15-3.4 # Use a PostGIS-enabled image (Postgres 15, PostGIS 3.4)
    container_name: nightbff_postgres_dev
    restart: always
    environment:
      POSTGRES_USER: nightbff_user
      POSTGRES_PASSWORD: your_strong_password # <-- CHANGE THIS!
      POSTGRES_DB: nightbff_dev
    ports:
      - "5432:5432" # Map container port 5432 to host port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nightbff_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nightbff_user -d nightbff_dev"]
      interval: 10s

  redis:
    image: redis:7-alpine
    container_name: nightbff_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nightbff_network
    restart: always

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  nightbff_network:
    driver: bridge 