name: Setup Backend Environment
description: Common setup steps for NightBFF backend workflows
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  install-deps:
    description: 'Whether to run npm ci'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Load CI env stub
      shell: bash
      run: cat ci/.env.stub >> "$GITHUB_ENV"

    - name: Ensure no nested submodules
      shell: bash
      run: |
        set -euo pipefail
        if git submodule--helper list | grep -q "nightbff-integration" 2>/dev/null; then
          echo "::error::Integration repo must not appear as submodule inside backend"
          exit 1
        fi

    - name: Use Node.js ${{ inputs.node-version }}
      if: inputs.install-deps == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'

    - name: Install dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: npm ci --retry 3

    - name: Build application
      shell: bash
      run: npm run build

    - name: Validate environment variables
      shell: bash
      run: npm run env:lint || echo "env:lint script not found, skipping"

    - name: Run dotenv-linter
      shell: bash
      run: npx dotenv-linter config/env/*.env || echo "No env files found, skipping"