version: '3.8'

services:
  mock_google_maps:
    build:
      context: ../mock-google-maps # Path to the mock server application
      dockerfile: Dockerfile
    container_name: mock_google_maps
    ports:
      - "3030:3000" # Exposing mock server on host port 3030, container runs on 3000
    restart: unless-stopped
    environment:
      # Add any necessary environment variables for the mock server
      LOG_LEVEL: info

 