global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: [
          'node_exporter_db:9100', 
          'node_exporter_app:9100', 
          'node_exporter_workers:9100',
          'node_exporter_loadgen:9100'
          # Add more targets as we deploy node_exporter to other instances
        ]

  - job_name: 'cadvisor'
    static_configs:
      - targets: [
          'cadvisor_db:8080',
          'cadvisor_app:8080',
          'cadvisor_workers:8080'
          # Add more cAdvisor targets as needed for each Docker host
        ]
        
  # We will add job configurations for application metrics later 