name: Build and Push Backend to GHCR

on:
  push:
    branches:
      - 'integration/**'
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/OWNER_PLACEHOLDER/nightbff-backend
          tags: |
            # Create a tag for the integration branch based on the short commit SHA
            type=sha,prefix=int-,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app # Assumes the Dockerfile is in the 'app' directory
          file: ./app/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 