name: CI – Backend Hardening

on:
  pull_request:
    paths:
      - 'app/**'
      - '.github/workflows/ci-backend.yml'
  push:
    branches: [ main, develop, 'integration/**' ]
    paths:
      - 'app/**'
      - '.github/workflows/ci-backend.yml'

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test-backend:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: nightbff_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U admin" --health-interval 5s --health-timeout 3s --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Backend Environment
        uses: ./.github/actions/setup-backend

      - name: Choose free Postgres port
        run: bash scripts/ci/choose-pg-port.sh

      - name: Run SeederService idempotency test (required check)
        working-directory: app
        run: npm test -- --testNamePattern="SeederService idempotency" --runInBand

      - name: Run unit & integration tests
        working-directory: app
        run: npm test -- --runInBand

  lint-cross-platform:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Backend Environment
        uses: ./.github/actions/setup-backend
        with:
          install-deps: 'true'

      - name: Run lint checks only
        working-directory: app
        run: npm run lint 