name: Seeder & Migration Guard

on:
  pull_request:
    paths:
      - '**/*.ts'
      - '**/docker-compose*.yml'
      - 'config/env/**'
      - '.github/workflows/ci-seeder-guard.yml'

concurrency:
  group: seeder-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test-seeder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Backend Environment
        uses: ./.github/actions/setup-backend

      - name: Guard against rogue seed scripts
        run: |
          cd app
          npm run ci:guard:seeds

      - name: Run Seeder idempotency test
        run: |
          cd app
          npm test -- -t "SeederService idempotency" 